language: php

php:
  - 7.0

sudo:
  - false

install:
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache